apiVersion: apps/v1
kind: Deployment
metadata:
  name: zootopia-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zootopia
  template:
    metadata:
      labels:
        app: zootopia
    spec:
      containers:
      - name: zootopia
        image: zootopia/app:1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "256Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
            ephemeral-storage: "512Mi" 
